spring:
  application:
    name: sys-module

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys_module?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
  profiles:
    active: local

server:
  port: 8099

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml  # mapper文件的扫描位置
  type-aliases-package: com.wzh.domain   # 别名扫描包
  configuration:
    map-underscore-to-camel-case: true  # 是否开启下划线和驼峰的映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  # 实体类有配置,如下可配置可不配置
  global-config:
    db-config:
      id-type: auto  # id为自增主键
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz0123456789ABCD
  # 令牌有效期（默认30分钟）
  expireTime: 30